### ISSUE TITLE
charger turned-off for unknown reason

### ISSUE THREAD

**Issue by troullll** [ddaddy/Tesla-Smart-Charging#4]
![image](https://github.com/user-attachments/assets/1a5275b9-a797-4dc0-bf8b-3ef38be78c4c)
hi, a few days after some different situations, I have this new issue (30 traces only so I can't check it),
any idea ? thanks

**Comment by ddaddy** [comment]
Sorry, I only speak a little French so don't fully understand your screenshot.
At 09:40 I doubt there is sufficient solar to charge?

Also, the lines about the charge latch seem strange. Could you have had a very brief power cut?

**Comment by troullll** [comment]
ok,
charger turned-off at the top of my screenshot, turned-on at the bottom. so weird...

![image](https://github.com/user-attachments/assets/f0866c25-09e9-475d-b420-9ee6bbc21bad)
yes, 1 spare Amp at 9:40

yes, I always have those lines asleep / charger door / port latch
why Asleep is "on" ? it seems Polling doesn't work... how could I check if it works ?

**Comment by troullll** [comment]
could we add a Wake-Up or Force Update action before any Tesla Smart Charge automation  ?

**Comment by ddaddy** [comment]
I think them lines run backwards? The most recent at the top.

I have already added some Polling automations which reduce the polling time during the day. Have you installed them?

**Comment by ddaddy** [comment]
Also, I *think* that when a command is sent to the car, it is woken up and all data refreshed.
That is handled by the Tesla integration.

**Comment by troullll** [comment]
installed and tested, Polling Time effectively change.
the Charger sensor is not up to date when automation runs it ... ok, data is delayed by the polling itself,
but I really think when the Tesla is deep "Asleep", we should add a binary_sensor.charging check, to ensure automation isn't changing amps as the Tesla effectively is not charging, it happened some times

**Comment by ddaddy** [comment]
Ok, as my car never sleeps for some reason 🤷‍♂️ (An old Model S) I never see this issue.
Reading the instructions for the Tesla HA Integration again, I see that it doesn't intentionally wake the car up. The only way to do this is by sending a command like 'lock doors' and this wakes the car.

I'll add to the automation, that if the car is asleep, send this command instead of doing any of the charging actions. Then 10 seconds later when it runs again, it should have the data it needs to proceed with charging.

**Comment by ddaddy** [comment]
This would actually mean, that as soon as the sun comes up, the automation will wake the car up and then it'll likely never sleep again during the day if it's at home. Is that ok?

**Comment by ddaddy** [comment]
Ok, i've added what I think is a better workaround.
If the automation wants to start charging:
```
Enough spare amps to charge
Charger is off
Battery level is below charge limit
```
and
```
Car is asleep
```

Then it will just send the `Wake Up` command to the car.

Then when the automation runs again after 10 seconds, the car should be in a state ready to accept the charge requests.


You'll need to go through the file again and replace all occurrences of `jess` with your car name and setup your variables etc..

**Comment by troullll** [comment]
got it.
I think when the Tesla start to charge at 1A, it stays at "starting charge", so binary_sensor.charging stays off.
I set the minimum_start_amps at 2, and it is ok.
Anyone else ?

**Comment by troullll** [comment]
oh sorry, I had not seen your answers, I'll check that !

**Comment by troullll** [comment]
> Ok, as my car never sleeps for some reason 🤷‍♂️ (An old Model S) I never see this issue. Reading the instructions for the Tesla HA Integration again, I see that it doesn't intentionally wake the car up. The only way to do this is by sending a command like 'lock doors' and this wakes the car.
> 
> I'll add to the automation, that if the car is asleep, send this command instead of doing any of the charging actions. Then 10 seconds later when it runs again, it should have the data it needs to proceed with charging.

ok ,good idea



> This would actually mean, that as soon as the sun comes up, the automation will wake the car up and then it'll likely never sleep again during the day if it's at home. Is that ok?

ok anyway

> Ok, i've added what I think is a better workaround. If the automation wants to start charging:
> 
> ```
> Enough spare amps to charge
> Charger is off
> Battery level is below charge limit
> ```
> 
> and
> 
> ```
> Car is asleep
> ```
> 
> Then it will just send the `Wake Up` command to the car.
> 
> Then when the automation runs again after 10 seconds, the car should be in a state ready to accept the charge requests.
> 
> You'll need to go through the file again and replace all occurrences of `jess` with your car name and setup your variables etc..

ok, I'll check this, thanks

**Comment by ddaddy** [comment]
Ignore my first 2 comments as i've made it only wake the car if the automation is actually wanting to start the charge.
And I also found the 'Wake Up' button in the integration, although the docs suggest you have to send a command to wake up.

If you find it not waking up, let me know and i'll change it to send a door lock command instead.

**Comment by troullll** [comment]
yes I'm reading your changes.
BTW, do you think the charger latch thing is an issue ?
![image](https://github.com/user-attachments/assets/218d9fa7-6b4f-4217-afe5-7ca2f94da5a6)

**Comment by ddaddy** [comment]
I don't know what would cause that. I would suggest a power cut, but it seems to happen too often for you.

Maybe try setting the minimum charge to 2a instead of 1a.

**Comment by troullll** [comment]
yes I already set the minimum_start_amps at 2, and it is ok to get the correct charger state.
I copypasted your Wake Up changes (minus Jess), I'll test it tomorrow hehe

**Comment by troullll** [comment]
![image](https://github.com/user-attachments/assets/4f243bb5-a9af-4e0c-af9f-f9736ebb9567)
sorry, same thing this morning .
![image](https://github.com/user-attachments/assets/c99167bf-0485-4d8e-96f0-19fd5d0ae21e)
why does the option 2 did turned off the charger switch ? I checked the "option 2" code :
  - conditions:
      - condition: template
        value_template: "{{ spare_amps >= minimum_start_amps }}"
      - condition: state
        entity_id: switch.charger
        state: "off"
      - condition: template
        value_template: "{{ charge_limit > battery_level }}"
    sequence:
      - data:
          name: "[Tesla Smart Charge]"
          message: >-
            Charger is off and we have {{ spare_amps }} spare amps. Attempting
            to start charge
        action: logbook.log
      - choose:
          - conditions:
              - condition: state
                entity_id: timer.turn_off_car_charger
                state: active
            sequence:
              - target:
                  entity_id: timer.turn_off_car_charger
                action: timer.cancel
                data: {}
      - target:
          entity_id: number.charging_amps
        data:
          value: "{{ spare_amps }}"
        action: number.set_value
      - target:
          entity_id: switch.charger
        action: switch.turn_on
        data: {}

**Comment by ddaddy** [comment]
I don't know 🤷‍♂️ There is no code there to turn it off.

Do you have any other automations that might turn it off?
Does it only happens once in the morning, then everything works ok after?

**Comment by troullll** [comment]
indeed on the trace of your automation ! how ?
btw, I suspect the charger switch bug. I manually turned on the charger this morning, and it switched off itself 2s after.
Wondering if it's caused by a Tesla Integration bug, as the interaction on our Tesla Apps is Start Charge OR Stop charge (buttons) and not a switch neither a toggle...
I will perform these tests :
alias: test switch toggle
description: ""
triggers: []
conditions: []
actions:
  - type: turn_on
    device_id: 65e6446555340f0b71c0d7ac6a62132c
    entity_id: 1ef66a2a8b3de3ba688f81363dde937c
    domain: switch
  - type: turn_off
    device_id: 65e6446555340f0b71c0d7ac6a62132c
    entity_id: 1ef66a2a8b3de3ba688f81363dde937c
    domain: switch
  - type: toggle
    device_id: 65e6446555340f0b71c0d7ac6a62132c
    entity_id: 1ef66a2a8b3de3ba688f81363dde937c
    domain: switch
  - action: switch.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: switch.charger
  - action: switch.toggle
    metadata: {}
    data: {}
    target:
      entity_id: switch.charger
mode: single

**Comment by troullll** [comment]
it happened twice more this morning (after few seconds)
![image](https://github.com/user-attachments/assets/976cea70-89cb-405e-a52d-5e8ea57bed11)

**Comment by ddaddy** [comment]
If the charger turns off after 2 seconds when you manually turn it on then it can't be an issue with this automation.

Try disabling all the polling automations, the `charging_off_when_plugged_in` automation and all the others like the Stop charging at sunset.

**Comment by troullll** [comment]
> indeed on the trace of your automation ! how ? btw, I suspect the charger switch bug. I manually turned on the charger this morning, and it switched off itself 2s after. Wondering if it's caused by a Tesla Integration bug, as the interaction on our Tesla Apps is Start Charge OR Stop charge (buttons) and not a switch neither a toggle... I will perform these tests : alias: test switch toggle description: "" triggers: [] conditions: [] actions:
> 
>     * type: turn_on
>       device_id: 65e6446555340f0b71c0d7ac6a62132c
>       entity_id: 1ef66a2a8b3de3ba688f81363dde937c
>       domain: switch
> 
>     * type: turn_off
>       device_id: 65e6446555340f0b71c0d7ac6a62132c
>       entity_id: 1ef66a2a8b3de3ba688f81363dde937c
>       domain: switch
> 
>     * type: toggle
>       device_id: 65e6446555340f0b71c0d7ac6a62132c
>       entity_id: 1ef66a2a8b3de3ba688f81363dde937c
>       domain: switch
> 
>     * action: switch.turn_on
>       metadata: {}
>       data: {}
>       target:
>       entity_id: switch.charger
> 
>     * action: switch.toggle
>       metadata: {}
>       data: {}
>       target:
>       entity_id: switch.charger
>       mode: single

no issue

**Comment by troullll** [comment]
> If the charger turns off after 2 seconds when you manually turn it on then it can't be an issue with this automation.
> 
> Try disabling all the polling automations, the `charging_off_when_plugged_in` automation and all the others like the Stop charging at sunset.

disabled all these ones
wait and see

**Comment by troullll** [comment]
ok, I checked different things:
after disabling all the polling automations that turn off the charger,
I tried to disable polling : it still works. 
things were ok : the switch_charger turned on each morning, even polling off.
charger switched off when "not enough juice" ok, even polling off.
the thing is polling drains a lot ! in one day, I can only charge a few percents that are drained by polling... but I need polling !
so I enable polling some times, even for a few seconds, to collect data, because wake_up and force_update DOES NOT work. even 11 minutes later...

a few questions : why asking me to deactivate your polling automations ? Interfering with service "Integration" polling ? Does it replace it ?
Could you have an automation that polls the Tesla only before charge start/ after charge stop ? (vicious circle I think)

I'm a bit lost at this stage, many things work good, but I had this "2 seconds apparently switched-off charger" this morning, with a new information : Tesla is actually charging, but the switch appears off (polling was off, but it worked yesterday even off !)
Thanks, I tried to be clear...

**Comment by ddaddy** [comment]
Your comment is really not clear to me.

I told you to disable the polling automations, just to try and narrow down what might be turning your charger off.

if it says it’s turning off, but it keeps charging, I wouldn’t worry about it 🤷🏼‍♂️

If your polling interval is too long, then HA can’t know what the car is doing.
